---
- name: "Security Group List"
  azure.azcollection.azure_rm_securitygroup_info:
    resource_group: "{{ kentik_az_resourcegroupname }}"
  register: az_sec_group_list

- name: "Enable Flow Logs"
  shell: >
    az network watcher flow-log create
    --location {{ location }}
    --resource-group {{ kentik_az_resourcegroupname }}
    --nsg {{ item.name }}
    --storage-account {{ kentik_az_storageaccount }}
    --name {{ item.name }}
    --format JSON
    --log-version 2
    --retention 2
    --interval {{ kentik_az_nsg_store_interval }}
  loop: "{{ az_sec_group_list.securitygroups }}"
  changed_when: false
