---
- name: "Get Resource Group Reader role definition"
  azure_rm_roledefinition_info:
    scope: "{{ resourcegroup_scope }}"
    role_name: "Reader"
  register: resourcegroupreader

- name: "ResourceGroup assignment list"
  azure.azcollection.azure_rm_roleassignment_info:
    scope: "{{ resourcegroup_scope }}"
  register: rgassignmentlist

- name: Set emply list for Kentik assignments to ResourceGroup"
  set_fact:
    kentik_assigment_rg: []

- name: "Check if need to assign role to ResourceGroup"
  set_fact:
    kentik_assigment_rg: "{{ kentik_assigment_rg + [item.name] }}"
  when:
    - kentik_az_principal_id == item.principal_id
    - resourcegroup_scope == item.scope
  loop: "{{ rgassignmentlist.roleassignments }}"

- name: "Assign Kentik access to ResourceGroup"
  azure_rm_roleassignment:
    scope: "/subscriptions/{{ kentik_az_sub }}/resourceGroups/{{ kentik_az_resourcegroupname }}"
    assignee_object_id: "{{ kentik_az_principal_id }}"
    role_definition_id: "{{ resourcegroupreader.roledefinitions[0].id }}"
  when: kentik_assigment_rg|length == 0
